[project]
name = "notification-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "aiohttp>=3.13.2",
    "environs>=14.5.0",
    "python-telegram-bot>=22.5",
]
